Make use of getPath to avoid '//' in path names
Some functions receiving a path as argument were not normalizing
this path, which may cause some functions fail.
Normalizing all paths using the member function
getPath makes code more readable.

For instance following function call fail because path ends with '/':

```
meta set /ilc/user/c/calanchac/stdhep/E500/ Energy 500

Error: Server error while serving setMetadata: '/ilc/user/c/calanchac/stdhep/E500/'
```