fix (WMS): Race condition in ExecutorState.getIdleExecutor when new executors are added
```python
2021-11-01 06:31:55,181252 lbvobox308.cern.ch WorkloadManagement/OptimizationMind ERROR Uncaught exception when serving Connect Function conn_connected
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 406, in _rh_executeConnectionCallback
    uReturnValue = oMethod(self.__trid, *args)
  File "/opt/dirac/pro/DIRAC/Core/Base/ExecutorMindHandler.py", line 161, in conn_connected
    self.__eDispatch.addExecutor(trid, kwargs["executorTypes"])
  File "/opt/dirac/pro/DIRAC/Core/Utilities/ExecutorDispatcher.py", line 425, in addExecutor
    self.__fillExecutors(eType)
  File "/opt/dirac/pro/DIRAC/Core/Utilities/ExecutorDispatcher.py", line 797, in __fillExecutors
    eId = self.__states.getIdleExecutor(eType)
  File "/opt/dirac/pro/DIRAC/Core/Utilities/ExecutorDispatcher.py", line 106, in getIdleExecutor
    for eId in self.__typeToId[eType]:
RuntimeError: Set changed size during iteration
```